Models/HomeViewModel.cs
using System.Collections.Generic;
using TrainingMVC.Model.Entity;

namespace TrainingMVC.Model
{
    public class HomeViewModel
    {
        public IEnumerable<Department> Departments { get; set; }
        public IEnumerable<Employee> Employees { get; set; }
        public IEnumerable<Designation> Designations { get; set; }
    }
}

Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Training.DataAccess.Repositories;
using TrainingMVC.Model.DTO;
using TrainingMVC.Model.Entity;

namespace TrainingMVC.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public DepartmentController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // GET: Department
        public async Task<IActionResult> Index()
        {
            var departments = await _unitOfWork.DepartmentRepo.GetAll();
            return View(departments);
        }

        // GET: Department/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Department/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(DeptListDTO departmentDto)
        {
            if (ModelState.IsValid)
            {
                var department = new Department
                {
                    Name = departmentDto.Name
                };
                _unitOfWork.DepartmentRepo.Add(department);
                await _unitOfWork.SaveAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(departmentDto);
        }

        // GET: Department/Edit/{id}
        public async Task<IActionResult> Edit(string id)
        {
            var department = await _unitOfWork.DepartmentRepo.GetById(id);
            if (department == null)
            {
                return NotFound();
            }
            return View(department);
        }

        // POST: Department/Edit/{id}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, Department department)
        {
            if (id != department.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _unitOfWork.DepartmentRepo.Edit(department);
                await _unitOfWork.SaveAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(department);
        }


        // GET: Department/Delete/{id}
        public async Task<IActionResult> Delete(string id)
        {
            var department = await _unitOfWork.DepartmentRepo.GetById(id);
            if (department == null)
            {
                return NotFound();
            }
            return View(department);
        }

        // POST: Department/Delete/{id}
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var department = await _unitOfWork.DepartmentRepo.GetById(id);
            if (department != null)
            {
                _unitOfWork.DepartmentRepo.Delete(department);
                await _unitOfWork.SaveAsync();
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/DesignationController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Training.DataAccess.Repositories;
using Training.Model.DTO;
using TrainingMVC.Model.Entity;

namespace TrainingMVC.Controllers
{
    public class DesignationController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public DesignationController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // GET: Designation
        public async Task<IActionResult> Index()
        {
            var designations = await _unitOfWork.DesignationRepo.GetAll();
            return View(designations);
        }

        // GET: Designation/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Designation/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(DesignationDto designationDto)
        {
            if (ModelState.IsValid)
            {
                var designation = new Designation
                {
                    Name = designationDto.Name
                };
                _unitOfWork.DesignationRepo.Add(designation);
                await _unitOfWork.SaveAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(designationDto);
        }

        // GET: Designation/Edit/{id}
        public async Task<IActionResult> Edit(string id)
        {
            var designation = await _unitOfWork.DesignationRepo.GetById(id);
            if (designation == null)
            {
                return NotFound();
            }

            var designationDto = new DesignationDto
            {
                Id = designation.Id.ToString(),
                Name = designation.Name
            };
            return View(designationDto);
        }

        // POST: Designation/Edit/{id}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, DesignationDto designationDto)
        {
            if (id != designationDto.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var designation = new Designation
                {
                    Id = designationDto.Id,
                    Name = designationDto.Name
                };

                _unitOfWork.DesignationRepo.Edit(designation);
                await _unitOfWork.SaveAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(designationDto);
        }

        // GET: Designation/Delete/{id}
        public async Task<IActionResult> Delete(string id)
        {
            var designation = await _unitOfWork.DesignationRepo.GetById(id);
            if (designation == null)
            {
                return NotFound();
            }
            return View(designation);
        }

        // POST: Designation/Delete/{id}
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var designation = await _unitOfWork.DesignationRepo.GetById(id);
            if (designation != null)
            {
                _unitOfWork.DesignationRepo.Delete(designation);
                await _unitOfWork.SaveAsync();
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using TrainingMVC.Model.DTO;
using TrainingMVC.Model.Entity;
using Training.DataAccess.Repositories;

public class EmployeeController : Controller
{
    private readonly IUnitOfWork _unitOfWork;

    public EmployeeController(IUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }

    // GET: Employee
    public async Task<IActionResult> Index()
    {
        var employees = await _unitOfWork.EmployeeRepo.GetAll();
        var employeeDtos = employees.Select(e => new EmpListDTO
        {
            Id = e.Id,
            Name = e.Name,
            Address = e.Address,
            City = e.City,
            Phone = e.Phone,
            DeptId = e.DeptId
        }).ToList();

        return View(employeeDtos);
    }

    // GET: Employee/Create
    public IActionResult Create()
    {
        return View();
    }

    // POST: Employee/Create
    [HttpPost]
    public async Task<IActionResult> Create(Employee employee)
    {
        if (ModelState.IsValid)
        {
            _unitOfWork.EmployeeRepo.Add(employee);
            await _unitOfWork.SaveAsync();
            return RedirectToAction(nameof(Index));
        }
        return View(employee);
    }

    // GET: Employee/Edit/5
    public async Task<IActionResult> Edit(string id)
    {
        var employee = await _unitOfWork.EmployeeRepo.GetById(id);
        if (employee == null)
        {
            return NotFound();
        }
        return View(employee);
    }

    // POST: Employee/Edit/5
    [HttpPost]
    public async Task<IActionResult> Edit(Employee employee)
    {
        if (ModelState.IsValid)
        {
            _unitOfWork.EmployeeRepo.Edit(employee);
            await _unitOfWork.SaveAsync();
            return RedirectToAction(nameof(Index));
        }
        return View(employee);
    }

    // GET: Employee/Delete/5
    public async Task<IActionResult> Delete(string id)
    {
        var employee = await _unitOfWork.EmployeeRepo.GetById(id);
        if (employee == null)
        {
            return NotFound();
        }
        return View(employee);
    }

    // POST: Employee/Delete/5
    [HttpPost, ActionName("Delete")]
    public async Task<IActionResult> DeleteConfirmed(string id)
    {
        var employee = await _unitOfWork.EmployeeRepo.GetById(id);
        if (employee != null)
        {
            _unitOfWork.EmployeeRepo.Delete(employee);
            await _unitOfWork.SaveAsync();
        }
        return RedirectToAction(nameof(Index));
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Training.DataAccess.Repositories;
using TrainingMVC.Model.Entity;
using TrainingMVC.Model;

namespace TrainingMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public HomeController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // GET: Home/Index
        public async Task<IActionResult> Index()
        {
            var departments = await _unitOfWork.DepartmentRepo.GetAll();
            var employees = await _unitOfWork.EmployeeRepo.GetAll();
            var designations = await _unitOfWork.DesignationRepo.GetAll();

            // Create a ViewModel to pass all data to the view
            var viewModel = new HomeViewModel
            {
                Departments = departments,
                Employees = employees,
                Designations = designations
            };

            return View(viewModel);
        }
    }
}

Views/Home/Index.cshtml
@model TrainingMVC.Model.HomeViewModel

<div class="container mt-5">
    <h1 class="text-center mb-4">Home</h1>

    <div class="mb-5">
        <h2 class="text-primary">Departments</h2>
        <table class="table table-bordered table-hover">
            <thead class="table-dark">
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var department in Model.Departments)
                {
                    <tr>
                        <td>@department.Id</td>
                        <td>@department.Name</td>
                        <td>
                            <a class="btn btn-sm btn-info" href="@Url.Action("Edit", "Department", new { id = department.Id })">Edit</a>
                            <a class="btn btn-sm btn-danger" href="@Url.Action("Delete", "Department", new { id = department.Id })">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <a class="btn btn-primary mt-2" href="@Url.Action("Create", "Department")">Create New Department</a>
    </div>

    <div class="mb-5">
        <h2 class="text-primary">Employees</h2>
        <table class="table table-bordered table-hover">
            <thead class="table-dark">
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var employee in Model.Employees)
                {
                    <tr>
                        <td>@employee.Id</td>
                        <td>@employee.Name</td>
                        <td>
                            <a class="btn btn-sm btn-info" href="@Url.Action("Edit", "Employee", new { id = employee.Id })">Edit</a>
                            <a class="btn btn-sm btn-danger" href="@Url.Action("Delete", "Employee", new { id = employee.Id })">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <a class="btn btn-primary mt-2" href="@Url.Action("Create", "Employee")">Create New Employee</a>
    </div>

    <div class="mb-5">
        <h2 class="text-primary">Designations</h2>
        <table class="table table-bordered table-hover">
            <thead class="table-dark">
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var designation in Model.Designations)
                {
                    <tr>
                        <td>@designation.Id</td>
                        <td>@designation.Name</td>
                        <td>
                            <a class="btn btn-sm btn-info" href="@Url.Action("Edit", "Designation", new { id = designation.Id })">Edit</a>
                            <a class="btn btn-sm btn-danger" href="@Url.Action("Delete", "Designation", new { id = designation.Id })">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <a class="btn btn-primary mt-2" href="@Url.Action("Create", "Designation")">Create New Designation</a>
    </div>
</div>